// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4R4wpZ5hFOBwozgZx23Dn7UaYnCpaAnw',
    appId: '1:126304190155:web:3d5bc173c4a2fa3e58a54e',
    messagingSenderId: '126304190155',
    projectId: 'notatmelhoria',
    authDomain: 'notatmelhoria.firebaseapp.com',
    storageBucket: 'notatmelhoria.firebasestorage.app',
    measurementId: 'G-F6EJ27XSNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzHYVUaOKoEAg_rt5teSShCuxGKVYUbpI',
    appId: '1:126304190155:android:694189624f07591158a54e',
    messagingSenderId: '126304190155',
    projectId: 'notatmelhoria',
    storageBucket: 'notatmelhoria.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtCtX8xmxAD5R3K-xpbOylJK7o8kNGQeM',
    appId: '1:126304190155:ios:c54e9f26da8718ae58a54e',
    messagingSenderId: '126304190155',
    projectId: 'notatmelhoria',
    storageBucket: 'notatmelhoria.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationAgain',
  );
}
